### ISSUE TITLE
snd_soc_register_component cannot find when compiling

### ISSUE THREAD

**Issue by fastwave2004** [franzflasch/ar9331-i2s-alsa#2]
Hi Franz,
I run this code on linux3.38 ,snd_soc_register_component cannot find when compiling,so I changed "return snd_soc_register_component(&pdev->dev, &ath79_i2s_component, &ath79_i2s_dai, 1);" to  "return snd_soc_register_dai(&pdev->dev, &ath79_i2s_dai);" ,but when  insmod ath79-i2s.ko I got some error as below: 
Apr  2 16:43:11 OpenWrt kern.warn kernel: [ 3075.270000] ath79_i2s: Unknown symbol snd_soc_register_dai (err 0)
Apr  2 16:43:11 OpenWrt kern.warn kernel: [ 3075.280000] ath79_i2s: Unknown symbol snd_soc_unregister_dai (err 0)

what should I do to fix above error? thanks

**Comment by franzflasch** [comment]
Hi fastwave!

It seems you forgot to insmod the module which provides the symbols for snd_soc_register_dai. Maybe you forgot to insmod the kernel module soc-core.ko?

Regards,
Franz

**Comment by fastwave2004** [comment]
Hi Franz,
thanks for your information, I am using openwrt I use opkg install kmod-sound-soc-core to install soc-core ,but seems not works ,then I use insmod snd-soc-core.ko ,got below error ,I have no idea how to deal with those depences .

[ 4865.420000] snd_soc_core: Unknown symbol regmap_init_spi (err 0)
[ 4865.420000] snd_soc_core: Unknown symbol of_property_count_strings (err 0)
[ 4865.430000] snd_soc_core: Unknown symbol regmap_init_i2c (err 0)
[ 4865.440000] snd_soc_core: Unknown symbol of_property_read_string_index (err 0)

**Comment by franzflasch** [comment]
Hi fastwave!

Which codec do you use with your setup?

It seems you have dependencies to i2c and spi. Could you please test it with the wm8727 codec?. It is a very simple codec without any control interface.

Regards,
Franz

**Comment by fastwave2004** [comment]
Hi Franz,
I use wm8960 which need a I2C .Now the above issue has been resolved after installing some necessary .ko file ,such as  opkg install kmod-regmap and  insmod snd-soc-core.ko, all the modules you provided has been insert without error, so there is no issue in your package. Now I have an issue of i2c-gpio I don't know if you have seen this, thanks very much if you can help on it ,.I need I2C gpio bus but after installing i2c-gpio-custom.ko i2c-gpio.ko ,there are below error 
 [ 3744.770000] Custom GPIO-based I2C driver version 0.1.1
[ 7130.630000] i2c-gpio: probe of i2c-gpio.0 failed with error -16

**Comment by fastwave2004** [comment]
Hi Franz,
above issue hass been resolved ,because  SDA pin has been ocuppied .
